"""收集"""

from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

send_data = rank
print(f"process {rank} send data {send_data} to root...")
recv_data = comm.gather(send_data, root=0)
if rank == 0:
    print(f"process {rank} gather all data {recv_data}...")


# result:
# process 1 send data 1 to root...
# process 2 send data 2 to root...
# process 3 send data 3 to root...
# process 4 send data 4 to root...
# process 5 send data 5 to root...
# process 6 send data 6 to root...
# process 7 send data 7 to root...
# process 8 send data 8 to root...
# process 9 send data 9 to root...
# process 0 send data 0 to root...
# process 0 gather all data [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]...
