"""发散"""

from mpi4py import MPI

comm = MPI.COMM_WORLD
rank = comm.Get_rank()
size = comm.Get_size()

if rank == 0:
    data = list(range(10))
    print(f"process {rank} scatter data {data} to other processes")
else:
    data = None
data = comm.scatter(data, root=0)

print(f"process {rank} recv {data}...")


# result:
# process 0 scatter data [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] to other processes
# process 0 recv 0...
# process 2 recv 2...
# process 1 recv 1...
# process 3 recv 3...
# process 4 recv 4...
# process 5 recv 5...
# process 6 recv 6...
# process 7 recv 7...
# process 8 recv 8...
# process 9 recv 9...
